project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "/manager/app/src/main/res/values/strings.xml",
    "translation": "/manager/app/src/main/res/values-%two_letters_code%/strings.xml",
    "type": "android"
  }
]
